package com.bookwormbliss.app

import android.app.*
import android.content.*
import android.graphics.Color
import android.graphics.Typeface
import android.net.Uri
import android.os.Bundle
import android.view.*
import android.webkit.WebView
import android.widget.*
import com.bookwormbliss.app.core.epub.*
import com.bookwormbliss.app.core.library.*
import com.bookwormbliss.app.core.reader.*
import com.bookwormbliss.app.ui.common.Ui
import java.io.File

class MainActivity:Activity(){
    private lateinit var store:BookStore; private lateinit var root:FrameLayout; private var screen="home"; private var selectedBook:Book?=null; private var drawer:Dialog?=null
    private val importCode=4101
    override fun onCreate(b:Bundle?){super.onCreate(b);store=BookStore(this);buildShell();show("home")}
    private fun buildShell(){root=FrameLayout(this).apply{setBackgroundColor(getColor(R.color.app_background))};setContentView(root)}
    private fun show(name:String){screen=name;root.removeAllViews();if(name=="reader"&&selectedBook!=null){showReader(selectedBook!!);return};val layout=LinearLayout(this).apply{orientation=LinearLayout.VERTICAL;setBackgroundColor(getColor(R.color.app_background))};layout.addView(header(title(name)),LinearLayout.LayoutParams(-1,Ui.dp(this,64)));val body=FrameLayout(this);layout.addView(body,LinearLayout.LayoutParams(-1,0,1f));root.addView(layout);when(name){"home"->home(body);"library","reading","finished","unread","favorites","recently_added"->books(body,name);"authors","series"->authorsSeries(body,name);"stats"->stats(body);"folders"->placeholder(body,"Folders\nYour folder organization foundation is ready.");"settings"->settings(body)} }
    private fun title(s:String)=when(s){"home"->"Home";"library"->"Library";"reading"->"Currently Reading";"finished"->"Finished";"unread"->"Read";"favorites"->"Favorites";"recently_added"->"Recently Added";"authors"->"Authors";"series"->"Series";"stats"->"Reading Stats";"folders"->"Folders";"settings"->"Settings";else->"The Bookworm Bliss"}
    private fun header(t:String):View{val r=Ui.row(this).apply{setPadding(Ui.dp(this@MainActivity,12),0,Ui.dp(this@MainActivity,12),0);setBackgroundColor(getColor(R.color.app_surface_soft))};val menu=ImageButton(this).apply{setImageResource(android.R.drawable.ic_menu_sort_by_size);setBackgroundColor(Color.TRANSPARENT);setOnClickListener{openDrawer()}};r.addView(menu,LinearLayout.LayoutParams(Ui.dp(this,52),-1));val tx=Ui.text(this,t,18,true);tx.typeface=Typeface.create("serif",Typeface.BOLD);r.addView(tx,LinearLayout.LayoutParams(0,-1,1f));if(t in listOf("Library","Currently Reading","Finished","Read","Favorites","Recently Added")){val add=Ui.button(this,"+"){startImport()};r.addView(add,LinearLayout.LayoutParams(Ui.dp(this,64),Ui.dp(this,44)))};return r}
    private fun openDrawer(){if(drawer?.isShowing==true)return;val d=Dialog(this);drawer=d;val box=LinearLayout(this).apply{orientation=LinearLayout.VERTICAL;setPadding(Ui.dp(this@MainActivity,18),Ui.dp(this@MainActivity,28),Ui.dp(this@MainActivity,18),Ui.dp(this@MainActivity,18));setBackgroundColor(getColor(R.color.app_surface))};box.addView(Ui.text(this,"The Bookworm Bliss",22,true));box.addView(Ui.text(this,"Your reading space",12));Ui.divider(this).also{box.addView(it,LinearLayout.LayoutParams(-1,Ui.dp(this,1)))};val items=listOf("home" to "Home","library" to "Library","reading" to "Currently Reading","finished" to "Finished","unread" to "Read","favorites" to "Favorites","recently_added" to "Recently Added","authors" to "Authors","series" to "Series","stats" to "Reading Stats","folders" to "Folders","settings" to "Settings");items.forEach{(id,label)->val b=Button(this).apply{text=label;textSize=13f;gravity=Gravity.START or Gravity.CENTER_VERTICAL;setTextColor(getColor(R.color.app_text_primary));setBackgroundColor(Color.TRANSPARENT);setOnClickListener{d.dismiss();show(id)}};box.addView(b,LinearLayout.LayoutParams(-1,Ui.dp(this,48)))};d.setContentView(box);d.window?.setLayout(Ui.dp(this,300),-1);d.show();d.window?.setLayout(Ui.dp(this,320),-1)}
    private fun home(body:ViewGroup){val col=LinearLayout(this).apply{orientation=LinearLayout.VERTICAL;setPadding(Ui.dp(this@MainActivity,20),Ui.dp(this@MainActivity,20),Ui.dp(this@MainActivity,20),Ui.dp(this@MainActivity,20))};val books=store.all();col.addView(Ui.text(this,"Welcome back",28,true));col.addView(Ui.text(this,"A quiet place for your books.",14));col.addView(Ui.text(this,"Your Library",18,true));renderBooks(col,books.take(6),false);val add=Ui.button(this,"Add EPUB"){startImport()};col.addView(add);body.addView(UiScroll(col))}
    private fun books(body:ViewGroup,kind:String){val all=store.all();var list=when(kind){"reading"->all.filter{it.isCurrentlyReading&&it.progress<.98f};"finished"->all.filter{it.progress>=.98f};"unread"->all.filter{it.progress==0f&&!it.isCurrentlyReading};"favorites"->all.filter{it.isFavorite};"recently_added"->all.sortedByDescending{it.addedDate};else->all};val col=LinearLayout(this).apply{orientation=LinearLayout.VERTICAL;setPadding(Ui.dp(this@MainActivity,16),Ui.dp(this@MainActivity,12),Ui.dp(this@MainActivity,16),Ui.dp(this@MainActivity,20))};val controls=Ui.row(this);val sort=Spinner(this).apply{adapter=ArrayAdapter(this@MainActivity,android.R.layout.simple_spinner_dropdown_item,arrayOf("Recently Added","Recently Read","Title","Author","Progress"));onItemSelectedListener=object:AdapterView.OnItemSelectedListener{override fun onNothingSelected(p:AdapterView<*>?){};override fun onItemSelected(p:AdapterView<*>?,v:View?,pos:Int,id:Long){list=when(pos){1->list.sortedByDescending{it.lastOpened};2->list.sortedBy{it.title.lowercase()};3->list.sortedBy{it.author.lowercase()};4->list.sortedByDescending{it.progress};else->list.sortedByDescending{it.addedDate}};refreshBooks(col,list,false)}}};controls.addView(sort,LinearLayout.LayoutParams(0,48,1f));val listBtn=Ui.button(this,"List"){refreshBooks(col,list,false)};controls.addView(listBtn,LinearLayout.LayoutParams(64,48));val gridBtn=Ui.button(this,"Grid"){refreshBooks(col,list,true)};controls.addView(gridBtn,LinearLayout.LayoutParams(64,48));col.addView(controls);renderBooks(col,list,false);body.addView(UiScroll(col))}
    private fun renderBooks(col:LinearLayout,list:List<Book>,grid:Boolean){if(list.isEmpty()){col.addView(Ui.text(this,getString(R.string.no_books),15));return};if(grid){val gridBox=GridLayout(this).apply{columnCount=2;useDefaultMargins=false};list.forEach{b->val card=Ui.card(this);card.gravity=Gravity.CENTER;val cover=ImageView(this);cover.scaleType=ImageView.ScaleType.CENTER_CROP;if(b.coverPath!=null)cover.setImageURI(Uri.fromFile(File(b.coverPath!!)));else cover.setImageResource(android.R.drawable.ic_menu_gallery);card.addView(cover,LinearLayout.LayoutParams(Ui.dp(this,118),Ui.dp(this,170)));card.addView(Ui.text(this,b.title,14,true));card.addView(Ui.text(this,b.author,11));card.setOnClickListener{selectedBook=b;show("reader")};card.setOnLongClickListener{selectedBook=b;bookActions(b);true};val lp=GridLayout.LayoutParams().apply{width=0;height=Ui.dp(this@MainActivity,245);columnSpec=GridLayout.spec(GridLayout.UNDEFINED,1f);setMargins(6,6,6,6)};gridBox.addView(card,lp)};col.addView(gridBox)}else list.forEach{b->val card=Ui.card(this);val row=Ui.row(this);val cover=ImageView(this);cover.scaleType=ImageView.ScaleType.CENTER_CROP;if(b.coverPath!=null)cover.setImageURI(Uri.fromFile(File(b.coverPath!!)));else cover.setImageResource(android.R.drawable.ic_menu_gallery);row.addView(cover,LinearLayout.LayoutParams(Ui.dp(this,78),Ui.dp(this,110)));val info=LinearLayout(this).apply{orientation=LinearLayout.VERTICAL;setPadding(Ui.dp(this@MainActivity,12),0,0,0)};info.addView(Ui.text(this,b.title,16,true));info.addView(Ui.text(this,b.author,12));val p=ProgressBar(this,null,android.R.attr.progressBarStyleHorizontal).apply{max=100;progress=(b.progress*100).toInt()};info.addView(p,LinearLayout.LayoutParams(-1,Ui.dp(this,6)));info.addView(Ui.text(this,"${(b.progress*100).toInt()}%",11));row.addView(info,LinearLayout.LayoutParams(0,-2,1f));card.addView(row);card.setOnClickListener{selectedBook=b;show("reader")};card.setOnLongClickListener{selectedBook=b;bookActions(b);true};val lp=LinearLayout.LayoutParams(-1,-2);lp.setMargins(0,0,0,Ui.dp(this,12));col.addView(card,lp)}}
    private fun refreshBooks(col:LinearLayout,list:List<Book>,grid:Boolean){while(col.childCount>1)col.removeViewAt(1);renderBooks(col,list,grid)}
    private fun bookActions(b:Book){val labels=arrayOf("Open","Book details","Reading Nook",if(b.isFavorite)"Remove Favorite" else "Add Favorite","Remove Book");AlertDialog.Builder(this).setTitle(b.title).setItems(labels){_,which->when(which){0->show("reader");1->details(b);2->nook(b);3->{b.isFavorite=!b.isFavorite;store.save(b);show(screen)};4->{store.delete(b.id);show(screen)}}}.show()}
    private fun details(b:Book){val msg="${b.title}\n\nAuthor: ${b.author}\nPublisher: ${b.publisher?:("Unknown")}\nLanguage: ${b.language?:("Unknown")}\nYear: ${b.year?:"Unknown"}\nIdentifier: ${b.identifier?:"Unknown"}\n\n${b.description?:"No description."}";AlertDialog.Builder(this).setTitle("Book Details").setMessage(msg).setPositiveButton("Edit Metadata"){_,_->editMetadata(b)}.setNeutralButton("Reading Nook"){_,_->nook(b)}.setNegativeButton("Close",null).show()}
    private fun editMetadata(b:Book){val fields=LinkedHashMap<String,EditText>();val box=LinearLayout(this).apply{orientation=LinearLayout.VERTICAL;setPadding(24,0,24,0)};listOf("Title" to b.title,"Author" to b.author,"Publisher" to (b.publisher?:""),"Language" to (b.language?:""),"Year" to (b.year?.toString()?:""),"Description" to (b.description?:"")).forEach{(label,value)->box.addView(Ui.text(this,label,11,true));val e=EditText(this).apply{setText(value);textSize=14f};fields[label]=e;box.addView(e)};AlertDialog.Builder(this).setTitle("Edit Metadata").setView(box).setPositiveButton("Save"){_,_->b.title=fields["Title"]!!.text.toString().ifBlank{"Untitled"};b.author=fields["Author"]!!.text.toString().ifBlank{"Unknown Author"};b.publisher=fields["Publisher"]!!.text.toString().ifBlank{null};b.language=fields["Language"]!!.text.toString().ifBlank{null};b.year=fields["Year"]!!.text.toString().toIntOrNull();b.description=fields["Description"]!!.text.toString().ifBlank{null};store.save(b);show(screen)}.setNegativeButton("Cancel",null).show()}
    private fun nook(b:Book){val col=LinearLayout(this).apply{orientation=LinearLayout.VERTICAL;setPadding(24,16,24,16)};col.addView(Ui.text(this,"Reading Nook",24,true));col.addView(Ui.text(this,b.title,18,true));col.addView(Ui.text(this,"A dedicated workspace for reading history, journal entries, stamps and highlights.\n\nThis v1 establishes the visual/functional foundation so the full web-app Nook can be expanded without changing reader core contracts.",14));col.addView(Ui.button(this,"Resume Reading"){selectedBook=b;show("reader")});AlertDialog.Builder(this).setView(col).setPositiveButton("Close",null).show()}
    private fun authorsSeries(body:ViewGroup,kind:String){val list=store.all().mapNotNull{if(kind=="authors")it.author else it.publisher}.distinct().sorted();val col=LinearLayout(this).apply{orientation=LinearLayout.VERTICAL;setPadding(20,20,20,20)};col.addView(Ui.text(this,if(kind=="authors")"Authors" else "Series",24,true));list.forEach{col.addView(Ui.text(this,it,15,true));col.addView(Ui.divider(this))};body.addView(UiScroll(col))}
    private fun stats(body:ViewGroup){val books=store.all();val col=LinearLayout(this).apply{orientation=LinearLayout.VERTICAL;setPadding(20,20,20,20)};col.addView(Ui.text(this,"Reading Stats",24,true));col.addView(Ui.text(this,"Books in library: ${books.size}",15));col.addView(Ui.text(this,"Currently reading: ${books.count{it.isCurrentlyReading}}",15));col.addView(Ui.text(this,"Finished: ${books.count{it.progress>=.98f}}",15));col.addView(Ui.text(this,"Reading statistics visual foundation is ready for future session analytics.",13));body.addView(UiScroll(col))}
    private fun settings(body:ViewGroup){val col=LinearLayout(this).apply{orientation=LinearLayout.VERTICAL;setPadding(20,20,20,20)};col.addView(Ui.text(this,"Settings",24,true));col.addView(Ui.text(this,"Appearance",17,true));val themes=arrayOf("Alabaster (Warm Sepia)","Ivory (Light)","Nordic Eco","Candlelight (Parchment)","Onyx (Pitch Dark)","Midnight Slate");val theme=Spinner(this).apply{adapter=ArrayAdapter(this@MainActivity,android.R.layout.simple_spinner_dropdown_item,themes)};col.addView(Ui.text(this,"Reader theme",12));col.addView(theme);col.addView(Ui.text(this,"The theme registry is centralized in ReaderWebRenderer and can be expanded without screen rewrites.",12));col.addView(Ui.text(this,"Typography and spacing tokens are centralized in resources and reader settings.",12));body.addView(UiScroll(col))}
    private fun placeholder(body:ViewGroup,text:String){val col=LinearLayout(this).apply{orientation=LinearLayout.VERTICAL;gravity=Gravity.CENTER;setPadding(30,30,30,30)};col.addView(Ui.text(this,text,16,true));body.addView(col)}
    private fun UiScroll(v:View):ScrollView=ScrollView(this).apply{addView(v);setBackgroundColor(getColor(R.color.app_background))}
    private fun startImport(){startActivityForResult(Intent(Intent.ACTION_OPEN_DOCUMENT).apply{type="application/epub+zip";addCategory(Intent.CATEGORY_OPENABLE)},importCode)}
    override fun onActivityResult(requestCode:Int,resultCode:Int,data:Intent?){super.onActivityResult(requestCode,resultCode,data);if(requestCode==importCode&&resultCode==RESULT_OK&&data?.data!=null)importEpub(data.data!!)}
    private fun importEpub(uri:Uri){val r=EpubParser(this).parse(uri);if(r.document==null){AlertDialog.Builder(this).setTitle("Could not add book").setMessage(r.diagnostics.joinToString("\n"){it.message}).setPositiveButton("OK",null).show();return};val d=r.document!!;val id="book_${System.currentTimeMillis()}";val b=Book(id,d.title,d.author,d.coverPath,d.description,d.publisher,d.language,d.publishYear,d.identifier,0f,0,0,1,false,false,System.currentTimeMillis(),0,d.sourceFilename,d.extractedRoot);store.save(b);show("library")}
    private fun showReader(b:Book){root.removeAllViews();val outer=LinearLayout(this).apply{orientation=LinearLayout.VERTICAL;setBackgroundColor(Color.BLACK)};val top=Ui.row(this).apply{setBackgroundColor(getColor(R.color.app_surface_soft));setPadding(8,0,8,0)};val back=Button(this).apply{text="‹";textSize=28f;setBackgroundColor(Color.TRANSPARENT);setOnClickListener{show("library")}};top.addView(back,LinearLayout.LayoutParams(56,64));val title=Ui.text(this,"${b.title}\n${b.author}",13,true);top.addView(title,LinearLayout.LayoutParams(0,64,1f));val toc=Ui.button(this,"TOC"){readerToc(b)};top.addView(toc,LinearLayout.LayoutParams(80,48));val set=Ui.button(this,"Aa"){readerSettings(b)};top.addView(set,LinearLayout.LayoutParams(70,48));outer.addView(top);val web=WebView(this);outer.addView(web,LinearLayout.LayoutParams(-1,0,1f));val bottom=Ui.row(this).apply{setBackgroundColor(getColor(R.color.app_surface_soft));gravity=Gravity.CENTER};val prev=Ui.button(this,"‹"){renderer?.previousPage();updateReaderLabel()};val label=Ui.text(this,"Page",12,true);val next=Ui.button(this,"›"){renderer?.nextPage();updateReaderLabel()};bottom.addView(prev,LinearLayout.LayoutParams(72,48));bottom.addView(label,LinearLayout.LayoutParams(0,56,1f));bottom.addView(next,LinearLayout.LayoutParams(72,48));outer.addView(bottom);root.addView(outer);val rr=ReaderWebRenderer(web);renderer=rr;val doc=loadDocumentFromBook(b);if(doc!=null){rr.load(doc);web.postDelayed({rr.restore(com.bookwormbliss.app.core.location.ReaderPosition(b.spineIndex,b.pageIndex,0));updateReaderLabel(label,b)},600)} }
    private var renderer:ReaderWebRenderer?=null
    private fun loadDocumentFromBook(b:Book):EpubDocument?=try{val source=File(filesDir,"imports/${b.sourceFilename}");EpubParser(this).parseFile(source).document}catch(_:Exception){null}
    private fun updateReaderLabel(label:TextView?=null,b:Book?=selectedBook){label?.text="Page ${renderer?.currentPage()?:1} / ${renderer?.pageCount()?:1}"}
    private fun updateReaderLabel(){ }
    private fun readerToc(b:Book){val rr=renderer?:return;val labels=rr.toc().map{"${it.label}  •  Section ${it.spineIndex+1}"}.toTypedArray();AlertDialog.Builder(this).setTitle("Table of Contents").setItems(labels){_,which->rr.loadChapter(rr.toc()[which].spineIndex)}.setNegativeButton("Close",null).show()}
    private fun readerSettings(b:Book){val rr=renderer?:return;val box=LinearLayout(this).apply{orientation=LinearLayout.VERTICAL;setPadding(20,8,20,8)};val themes=arrayOf("alabaster","ivory","nordic_eco","candlelight","onyx","midnight_slate");val ts=Spinner(this).apply{adapter=ArrayAdapter(this@MainActivity,android.R.layout.simple_spinner_dropdown_item,themes)};val fs=SeekBar(this).apply{max=36;progress=6};val mode=Spinner(this).apply{adapter=ArrayAdapter(this@MainActivity,android.R.layout.simple_spinner_dropdown_item,arrayOf("horizontal","vertical"))};box.addView(Ui.text(this,"Theme",12,true));box.addView(ts);box.addView(Ui.text(this,"Font size",12,true));box.addView(fs);box.addView(Ui.text(this,"Reading mode",12,true));box.addView(mode);AlertDialog.Builder(this).setTitle("Reader Settings").setView(box).setPositiveButton("Apply"){_,_->rr.applySettings(ReaderSettings(ts.selectedItem.toString(),"serif",20+fs.progress,1.6f,24,"left",mode.selectedItem.toString()))}.setNegativeButton("Cancel",null).show()}
}
